stages:
  - sync

sync_git:
  stage: sync
  image: $REGISTRYURL_IMAGES/alpine:latest
  script:
    - apk add --no-cache git
    - git clone https://github.com/jahwag/gh2gl.git
    - cd gh2gl
    - git remote add gitlab $GITLAB_REPO_URL
    - git fetch origin
    - git checkout master
    - git pull origin master
    - git push gitlab master
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: manual
